trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use dotnet 3.1'
  inputs:
    version: 3.1.x

- task: UseDotNet@2
  displayName: 'Use dotnet 6.0'
  inputs:
    version: 6.0.x

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*ContosoUniversity.Test/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: MicrosoftSecurityDevOps@1
  displayName: 'Run Microsoft Security DevOps'