trigger:
- none

pool:
  vmImage: 'windows-2019'

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'any cpu'

stages:
- stage: build
  jobs:
  - job: run_build
    displayName: run build
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: VSBuild@1
      displayName: 'Build solution ContosoUniversity.CodedUITest/ContosoUniversity.CodedUITest.csproj'
      inputs:
        solution: ContosoUniversity.CodedUITest/ContosoUniversity.CodedUITest.csproj
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*ContosoUniversity.Test/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/WebApp'
        zipAfterPublish: True

    - task: CopyFiles@2
      displayName: 'Copy Files to: ArmTemplates'
      inputs:
        SourceFolder: 'ContosoUniversity.AzureResourceGroup'
        Contents: '**\*.json'
        TargetFolder: '$(build.artifactstagingdirectory)/ArmTemplates'

    - task: CopyFiles@2
      displayName: 'Copy Files to: Scripts'
      inputs:
        SourceFolder: Scripts
        TargetFolder: '$(build.artifactstagingdirectory)/Scripts'

    - task: CopyFiles@2
      displayName: 'Copy Files to: CodedUITest'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\ContosoUniversity.CodedUITest\bin\$(BuildConfiguration)\netcoreapp3.1'
        Contents: '**\*'
        TargetFolder: '$(build.artifactstagingdirectory)/CodedUITest'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact WebApp'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/WebApp'
        ArtifactName: WebApp

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact ArmTemplates'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/ArmTemplates'
        ArtifactName: ArmTemplates

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact Scripts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/Scripts'
        ArtifactName: Scripts

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact CodedUITest'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/CodedUITest'
        ArtifactName: CodedUITest

- stage: deploy_dev
  jobs:
  - deployment: DeployDev
    displayName: deploy to dev
    variables:
      Infos.Ambiente: 'DEV'
      Api.Address: 'https://contosouniversityexampleapi-dev.azurewebsites.net'
      ConnectionStrings.ContosoUniversityAPIContext: 'Server=tcp:leadro.database.windows.net,1433;Initial Catalog=ContosoUniversity;Persist Security Info=False;User ID=leadro;Password=P@ssw0rd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
      Infos.Versao: $(Build.BuildNumber)
    environment: 'contosouniversity-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: WebApp

          - task: AzureRmWebAppDeployment@4
            displayName: 'ContosoUniversityExample Api'
            inputs:
              azureSubscription: 'MS Internal'
              WebAppName: ContosoUniversityExampleApi
              deployToSlotOrASE: true
              ResourceGroupName: 'RG_ContosoUniversity'
              SlotName: dev
              packageForLinux: '$(Pipeline.Workspace)/WebApp/ContosoUniversity.API.zip'
              JSONFiles: '**/appsettings.json'
          
          - task: AzureRmWebAppDeployment@4
            displayName: 'ContosoUniversityExample WebApp'
            inputs:
              azureSubscription: 'MS Internal'
              WebAppName: ContosoUniversityExample
              deployToSlotOrASE: true
              ResourceGroupName: 'RG_ContosoUniversity'
              SlotName: dev
              packageForLinux: '$(Pipeline.Workspace)/WebApp/ContosoUniversity.WebApplication.zip'
              JSONFiles: '**/appsettings.json'

- stage: deploy_hml
  jobs:
  - deployment: DeployDev
    displayName: deploy to hml
    variables:
      Infos.Ambiente: 'HML'
      Api.Address: 'https://contosouniversityexampleapi-qa.azurewebsites.net'
      ConnectionStrings.ContosoUniversityAPIContext: 'Server=tcp:leadro.database.windows.net,1433;Initial Catalog=ContosoUniversity;Persist Security Info=False;User ID=leadro;Password=P@ssw0rd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
      Infos.Versao: $(Build.BuildNumber)
    environment: 'contosouniversity-qa'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: WebApp

          - task: AzureRmWebAppDeployment@4
            displayName: 'ContosoUniversityExample Api'
            inputs:
              azureSubscription: 'MS Internal'
              WebAppName: ContosoUniversityExampleApi
              deployToSlotOrASE: true
              ResourceGroupName: 'RG_ContosoUniversity'
              SlotName: qa
              packageForLinux: '$(Pipeline.Workspace)/WebApp/ContosoUniversity.API.zip'
              JSONFiles: '**/appsettings.json'
          
          - task: AzureRmWebAppDeployment@4
            displayName: 'ContosoUniversityExample WebApp'
            inputs:
              azureSubscription: 'MS Internal'
              WebAppName: ContosoUniversityExample
              deployToSlotOrASE: true
              ResourceGroupName: 'RG_ContosoUniversity'
              SlotName: qa
              packageForLinux: '$(Pipeline.Workspace)/WebApp/ContosoUniversity.WebApplication.zip'
              JSONFiles: '**/appsettings.json'

- stage: deploy_prd
  jobs:
  - deployment: DeployPrd
    displayName: deploy to prd
    variables:
      Infos.Ambiente: 'PRD'
      Api.Address: 'https://contosouniversityexampleapi.azurewebsites.net'
      ConnectionStrings.ContosoUniversityAPIContext: 'Server=tcp:leadro.database.windows.net,1433;Initial Catalog=ContosoUniversity;Persist Security Info=False;User ID=leadro;Password=P@ssw0rd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
      Infos.Versao: $(Build.BuildNumber)
    environment: 'contosouniversity-prd'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: WebApp

          - task: AzureRmWebAppDeployment@4
            displayName: 'ContosoUniversityExample Api'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'MS Internal'
              appType: 'webApp'
              WebAppName: 'ContosoUniversityExampleApi'
              packageForLinux: '$(Pipeline.Workspace)/WebApp/ContosoUniversity.API.zip'
              JSONFiles: '**/appsettings.json'
          
          - task: AzureRmWebAppDeployment@4
            displayName: 'ContosoUniversityExample WebApp'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'MS Internal'
              appType: 'webApp'
              WebAppName: 'ContosoUniversityExample'
              packageForLinux: '$(Pipeline.Workspace)/WebApp/ContosoUniversity.WebApplication.zip'
              JSONFiles: '**/appsettings.json'