trigger:
- none

pool:
  vmImage: 'windows-2019'

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'any cpu'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: |
     **/ContosoUniversity.API.csproj
     **/ContosoUniversity.WebApplication.csproj
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: |
     **/ContosoUniversity.API.csproj
     **/ContosoUniversity.WebApplication.csproj
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*ContosoUniversity.Test/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Publish - ContosoUniversity.API'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/ContosoUniversity.API.csproj'
    arguments: '--configuration $(BuildConfiguration) --output ContosoUniversity.API/bin/PublishOutput'
    zipAfterPublish: false
- task: DotNetCoreCLI@2
  displayName: 'Publish - ContosoUniversity.WebApplication'
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/ContosoUniversity.WebApplication.csproj'
    arguments: '--configuration $(BuildConfiguration) --output ContosoUniversity.WebApplication/bin/PublishOutput'
    zipAfterPublish: false
- task: Docker@1
  displayName: 'Build an image - ContosoUniversity.API'
  inputs:
    azureSubscriptionEndpoint: 'MS Internal'
    azureContainerRegistry: leadroregistry.azurecr.io
    dockerFile: ContosoUniversity.API/DockerfileBuild
    imageName: 'ContosoUniversity.API:$(Build.BuildId)'
    includeLatestTag: true
- task: Docker@1
  displayName: 'Push an image - ContosoUniversity.API'
  inputs:
    azureSubscriptionEndpoint: 'MS Internal'
    azureContainerRegistry: leadroregistry.azurecr.io
    command: 'Push an image'
    imageName: 'ContosoUniversity.API:$(Build.BuildId)'
- task: Docker@1
  displayName: 'Build an image - ContosoUniversity.WebApplication'
  inputs:
    azureSubscriptionEndpoint: 'MS Internal'
    azureContainerRegistry: leadroregistry.azurecr.io
    dockerFile: ContosoUniversity.WebApplication/DockerfileBuild
    imageName: 'ContosoUniversity.Web:$(Build.BuildId)'
    includeLatestTag: true
- task: Docker@1
  displayName: 'Push an image - ContosoUniversity.WebApplication'
  inputs:
    azureSubscriptionEndpoint: 'MS Internal'
    azureContainerRegistry: leadroregistry.azurecr.io
    command: 'Push an image'
    imageName: 'ContosoUniversity.Web:$(Build.BuildId)'
- task: CmdLine@1
  displayName: 'Replace Build Number - kubernetes-webapi.yaml'
  inputs:
    filename: bash
    arguments: '-c "sed -i ''s/BuildNumber/$(Build.BuildId)/g''  kubernetes-webapi.yaml'
- task: CmdLine@1
  displayName: 'Replace Build Number - kubernetes-webapp'
  inputs:
    filename: bash
    arguments: '-c "sed -i ''s/BuildNumber/$(Build.BuildId)/g''  kubernetes-webapp.yaml'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact - webapi'
  inputs:
    PathtoPublish: 'kubernetes-webapi.yaml'
    ArtifactName: Api
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact - webapp'
  inputs:
    PathtoPublish: 'kubernetes-webapp.yaml'
    ArtifactName: App