kind: Service
apiVersion: v1
metadata:
  name: contoso-university-api
spec:
  selector:
    app: contoso-university-api
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contoso-university-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: contoso-university-api
        tier: backend
        track: stable
    spec:
      containers:
        - name: contoso-university-api
          image: "leadroregistry.azurecr.io/contosouniversity.api:BuildNumber"
          ports:
            - name: http
              containerPort: 9000
      imagePullSecrets:
        - name: acr