kind: Service
apiVersion: v1
metadata:
  name: contoso-university-app
spec:
  selector:
    app: contoso-university-app
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contoso-university-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contoso-university-app
        tier: frontend
        track: stable
    spec:
      containers:
        - name: contoso-university-app
          image: "leadroregistry.azurecr.io/contosouniversity.webapplication:BuildNumber"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: acr