- hosts: localhost

  vars:
    resource_group: __resourceGroupName__
    location: __location__
    webapp_name: __webappName__

  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create App Service
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: myappplan
          is_linux: false
          sku: S1
          number_of_workers: 1