name: ContosoUniversity-Deployment

on:
  push:
    branches:
    - master

env:
  BuildConfiguration: Release
  BuildPlatform: any cpu
  WebAppName: ase-ContosoUniversityAPP
  WebApiName: ase-ContosoUniversityAPI
  AZ_RG_NAME: RG_ContosoUniversity
  AZ_RG_LOCATION: eastus

jobs:
  
  run_infra:
    name: create infra
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    
    - name: Create Resource Group
      run: |
        if [ $(az group exists --name ${{ env.AZ_RG_NAME }}) = false ]; then
          az group create --name ${{ env.AZ_RG_NAME }} --location ${{ env.AZ_RG_LOCATION }}
        else
            echo "Resource group already exists"
        fi
        
    - uses: Azure/cli@v1
      with:
        inlineScript: az deployment group create --resource-group ${{ env.AZ_RG_NAME }} --template-file ContosoUniversity.AzureResourceGroup/ARMTemplates/WebSite.json --parameters  ContosoUniversity.AzureResourceGroup/ARMTemplates/WebSite.parameters.json
  
  run_build:
    name: run build
    runs-on: windows-latest
    needs:
      - run_infra
    steps:
    
    - uses: actions/checkout@v3
    
    - uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration ${{ env.BuildConfiguration }}
    
    - name: Build ContosoUniversity.CodedUITest
      run: msbuild 'ContosoUniversity.CodedUITest/ContosoUniversity.CodedUITest.csproj' /p:configuration='${{ env.BuildConfiguration }}' /p:platform='${{ env.BuildPlatform }}'
    
    - name: Test
      run: dotnet test ContosoUniversity.Test\ContosoUniversity.Test.csproj --configuration ${{ env.BuildConfiguration }}
    
    - name: Publish API
      run: dotnet publish ContosoUniversity.API\ContosoUniversity.API.csproj --no-restore --no-build --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}/WebApi
    
    - name: Publish APP
      run: dotnet publish ContosoUniversity.WebApplication\ContosoUniversity.WebApplication.csproj --no-restore --no-build --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}/WebApp

    - name: 'Copy Files to: ArmTemplates'
      run: Copy 'ContosoUniversity.AzureResourceGroup/**\*.json' '${{ github.workspace }}/ArmTemplates'
    
    - name: 'Copy Files to: Scripts'
      run: Copy 'Scripts/' '${{ github.workspace }}/Scripts'
    
    #- name: 'Copy Files to: CodedUITest'
    #  run: Copy '${{ github.workspace }}\ContosoUniversity.CodedUITest\bin\${{ env.BuildConfiguration }}etcoreapp3.1/**\*' '${{ github.workspace }}/CodedUITest'
    
    - name: Publish Artifact WebApp
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/WebApp
        name: WebApp
    
    - name: Publish Artifact ArmTemplates
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/ArmTemplates
        name: ArmTemplates
    
    - name: Publish Artifact Scripts
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/Scripts
        name: Scripts
    
    - name: Publish Artifact CodedUITest
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/CodedUITest
        name: CodedUITest
  
  deploy_dev:
    name: deploy to dev
    runs-on: windows-latest
    needs:
      - run_build
    environment:
      name: contosouniversity-dev
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    
    - uses: actions/download-artifact@v2
      with:
        name: WebApp
    
    - name: ContosoUniversityExample Api
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebApiName }}
        package: ${{ env.Pipeline.Workspace }}/WebApp/ContosoUniversity.API.zip
        slot-name: dev
    
    - name: ContosoUniversityExample WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebAppName }}
        package: ${{ env.Pipeline.Workspace }}/WebApp/ContosoUniversity.WebApplication.zip
        slot-name: dev
  
  deploy_hml:
    # 'Note: Azure DevOps strategy>runOnce does not have an equivalent in GitHub Actions yet, and only the deploy steps are transferred to steps'
    name: deploy to hml
    runs-on: windows-latest
    needs:
      - deploy_dev
    environment:
      name: contosouniversity-qa
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    
    - uses: actions/download-artifact@v2
      with:
        name: WebApp
    
    - name: ContosoUniversityExample Api
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebApiName }}
        package: ${{ env.Pipeline.Workspace }}/WebApp/ContosoUniversity.API.zip
        slot-name: qa
    
    - name: ContosoUniversityExample WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebAppName }}
        package: ${{ env.Pipeline.Workspace }}/WebApp/ContosoUniversity.WebApplication.zip
        slot-name: qa
  
  deploy_uat:
    # 'Note: Azure DevOps strategy>runOnce does not have an equivalent in GitHub Actions yet, and only the deploy steps are transferred to steps'
    name: deploy to uat
    runs-on: windows-latest
    needs:
      - deploy_dev
    environment:
      name: contosouniversity-uat
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    
    - uses: actions/download-artifact@v2
      with:
        name: WebApp
    
    - name: ContosoUniversityExample Api
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebApiName }}
        package: ${{ env.Pipeline.Workspace }}/WebApp/ContosoUniversity.API.zip
        slot-name: uat
    
    - name: ContosoUniversityExample WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebAppName }}
        package: ${{ env.Pipeline.Workspace }}/WebApp/ContosoUniversity.WebApplication.zip
        slot-name: uat
  
  deploy_prd:
    # 'Note: Azure DevOps strategy>runOnce does not have an equivalent in GitHub Actions yet, and only the deploy steps are transferred to steps'
    name: deploy to prd
    runs-on: windows-latest
    needs:
      - deploy_hml
      - deploy_uat
    environment:
      name: contosouniversity-prd
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    
    - uses: actions/download-artifact@v2
      with:
        name: WebApp
    
    - name: ContosoUniversityExample Api
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebApiName }}
        package: ${{ env.Pipeline.Workspace }}/WebApp/ContosoUniversity.API.zip
    
    - name: ContosoUniversityExample WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WebAppName }}
        package: ${{ env.Pipeline.Workspace }}/WebApp/ContosoUniversity.WebApplication.zip